# Generated by Django 5.0.1 on 2024-05-20 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatflox', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='address',
            new_name='text',
        ),
    ]
