# Generated by Django 5.0.1 on 2024-05-20 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatflox', '0002_rename_address_location_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='text',
            new_name='address',
        ),
    ]
