# Generated by Django 5.0.1 on 2024-05-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatflox', '0004_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgmodel',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pgmodel',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
