# Generated by Django 5.0.1 on 2024-05-20 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatflox', '0005_pgmodel_city_pgmodel_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='PGPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pg_images/')),
                ('pg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flatflox.pgmodel')),
            ],
        ),
        migrations.AddField(
            model_name='pgmodel',
            name='pictures',
            field=models.ManyToManyField(to='flatflox.pgpicture'),
        ),
    ]
