# Generated by Django 5.0.1 on 2024-05-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatflox', '0006_pgpicture_pgmodel_pictures'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingCities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='working_cities/')),
            ],
        ),
    ]
